### PR TITLE
Fixes bad link

### PR DESCRIPTION
**Pull request by adriancole**
Zipkin server includes collector functionality, so might be the best link target.

### CODE REVIEW

**Comment by adriancole** [comment]
ps I signed the cla (clicking details verifies). maybe there's some eventual consistency going on

**Comment by adriancole** [comment]
ah.. ok silly "Edit button" doesn't attach my primary email address to the commit, and makes clahub cry.

should be GTG

**Comment by tlockney** [comment]
Thanks!

**Comment by tlockney** [comment]
Ugh, this time I hit the wrong button. ;~) Should be all good now.

**Pull request merged**
