### PR TITLE
Add support for timestamped annotations on Spans

### PR DESCRIPTION
**Pull request by nicmunroe**

### CODE REVIEW

**Comment by adriancole** [comment]
interesting. what led you here?

**Comment by nicmunroe** [comment]
@adriancole We already went through the major effort to get proper tag support (including auto-tagging instrumentation). Annotations were pretty simple in comparison, so I figured why not?

Plus I have a cool use case for these in Riposte - I'll probably post in Zipkin's gitter once it's done.

I also noticed Zipkin has some nice visuals when custom annotations are on a span. Might as well take advantage. :)

**Comment by nicmunroe** [comment]
@adriancole Yeah my plan for Riposte is similar to wire-send and wire-receive, although I want to mark when the first chunk and last chunk of the request arrive, and when the first chunk and last chunk of the response leave. This will let users know when a request was slow due to slow/flaky network connection between caller and server (something out of your control), vs. slowness elsewhere (something you likely can control).

I'd like to use Zipkin's annotation names for maximum compatibility if possible, but I'm having trouble figuring out what to do. The best docs I can find for these annotations is in the old Zipkin 1 `zipkin.Constants` class. It looks like what I'm going for is something in between `ss`, `sr`, `ssf`, and `srf`. But I don't want to mark when *every* chunk is received or sent, just the first and last chunks of the request and response (4 total).`sr` and `ss` could mark when the first chunk of the request is received and first chunk of the response sent, respectively. But what about the last chunks? I suppose I could use `srf` and `ssf` and Riposte users would just need to know the convention is to only add those for the last chunks, but that feels sketchy.

I don't suppose there's a `lsrf` and `lssf` hiding somewhere is there (for "last-server-receive-fragment" and "last-server-send-fragment")?

**Comment by adriancole** [comment]
I think this is up to you, but I feel inventing a concept for last annotation will be tech debt. If the rationale is that you don't want to add fragment annotations for all events, it isn't necessary to make up a new annotation to say that you are only using one event. The UI won't display this and it will also create new questions for folks exporting to zipkin and wonder what "lsrf" is which is only used in frameworks that not only use fragments, but decide to not annotate all of them. If there was any processing, I'd expect it to look for the last fragment annotation not one named last fragment. The reason is that annotations are already ordered by timestamp, and applied to a single host. If we did want to make analysis, we wouldn't want to bother people with an if statement :P

So tl;dr; my opinion is if you are concerned about the idea of not recording an annotation for all fragments, maybe start with lack of concern. There's no strict contract that says if you do this, you must also do for all fragments. We can also clarify the docs to say this if needed, but it is already loose enough to permit it.

https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L136

My 2p

PS @trustin @anuraaga I know you are also looking at using annotations for some netty events. It is a nice way to cheaply add details, though certainly lacking a full http model (ex the full events includes headers received which is implicit in most instrumentation, which makes span duration off. That's why some use separate spans for response processing as well). There's a balance between wanting to capture http lifecycle, which is huge, with enough details, and also be cheap.
https://docs.google.com/document/d/1yIo_zZvMyAS8J7bpCz85h-FISwU0Jr-Zu-POIvp7B9E/edit

**Comment by adriancole** [comment]
ps what I'm specifically trying to avoid is the following:
* new UI hints for this special case
* logic that would be (lssf.timestamp | max(ssf.timestamp)) when the latter would be portable with both concerns
* more things to explain to people or have questions about :)

In the process of doing the above, very interested in having more signal. Just wondering if there's a re-use possibility.

**Comment by adriancole** [comment]
PS I think I misunderstood the intent here, because I was thinking chunks like body fragments, whereas nic was thinking chunks like bytes that could be request line as well. I'll leave it to him to summarize

**Comment by nicmunroe** [comment]
Yeah, apologies for misusing "chunk". I was referring to initial bytes received/sent and last bytes received/sent for the entire request or response. This would therefore include requestline on the request and statusline on the response.

So with that in mind, I *think* wire-receive and wire-send annotations are accurate for what I'm trying to track? If so, I'd probably do `wr` for the initial bytes of the request and `wr.finish` for the final bytes, and `ws` for the initial bytes of the response and `ws.finish` for the final bytes.

**Comment by adriancole** [comment]
>
> So with that in mind, I *think* wire-receive and wire-send annotations
> are accurate for what I'm trying to track? If so, I'd probably do wr for
> the initial bytes of the request and wr.finish for the final bytes, and ws
> for the initial bytes of the response and ws.finish for the final bytes.
>
that's really interesting.. matches up pretty well and worth a try imho!

**Pull request merged**
