### PR TITLE
Add initial SpringBoot support.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by nicmunroe** [comment]
@alesj thank you for submitting a PR! Sorry it's taking so long to get back to you, things are very busy right now. I'll try to get to this soon but I can't guarantee anything as far as timeframe goes.

In the meantime it looks like you need a bit more test coverage, and I don't see a readme for the new module which is going to make it more difficult for me (and other users) to know what's available and how it's intended to be used. 

Also - is everything in here tied to Spring Boot, or are there features that could be pulled out for general Spring usage? In other words, should there be two new modules, one for `wingtips-spring`, and the other for `wingtips-spring-boot`?

**Comment by alesj** [comment]
@nicmunroe np wrt getting back ... if there is something I can help, let me know

I'll try to add some more test coverage and better readme (or readme at all :-)).

Yeah, a split makes sense -- although it's only gonna be a few classes in each module to start with.

I'm also working on OpenTracing a bit, if this is something that could be interesting.
e.g. to implement OT via Wingtips core --> wingtips-opentracing module

**Comment by nicmunroe** [comment]
@alesj do you still have interest in this? Do you object if I build on your commits to flesh out the tests and documentation/etc and take it over the line?

**Comment by alesj** [comment]
@nicmunroe hey, busy here as well, hence a bit sidetracked this for a while.
But yeah, sure, go ahead.
And (hopefully) I'll try come back to it asap.

**Comment by nicmunroe** [comment]
@alesj just a quick FYI that I've done a bunch of work on this and should have a PR out soon (maybe tomorrow?) that builds on yours, adds tests/javadocs/readmes, rejiggers some stuff, and adds a few extra features.

**Comment by nicmunroe** [comment]
Closing this now that #51 is merged. Thanks again for doing this PR!

**Pull request closed without merging**
