### PR TITLE
Adding tags for uri, response code, error and method

### PR DESCRIPTION
**Pull request by brandoncurrie**
Added default tags for every request that comes through the filter. Also split out some functions that might want to be overridden:
- What determines an error tag to be set to true
- The human-readable name for a `Span`
- The URI/URL pattern used as the value for http.url

### CODE REVIEW

**Comment by brandoncurrie** [comment]
I was just reading through the Brave implementation docs: https://github.com/openzipkin/brave/blob/414d741db9d4f16f78169d704fea670bcee0b18e/instrumentation/http/README.md#span-data-policy

I'm going to add the tags to the client span as well.  Right now this just implements the server spans.

**Comment by brandoncurrie** [comment]
I believe I've got this to a good spot.  Wrapping inbound server requests with tags was a relatively straightforward change but once it opened up to the downstream client requests I had to instrument many more libraries with a tagging strategy.  I'd love some feedback on the approach and its portability and ease of configuration.

**Comment by nicmunroe** [comment]
@brandoncurrie thanks for the PR! I'm trying to carve out some time over the next few days to go over this.

**Comment by nicmunroe** [comment]
Closing this PR in favor of #82, which builds on top of @brandoncurrie's commits.

**Pull request closed without merging**
